# Generated by Django 2.2.7 on 2019-11-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('name', models.TextField(blank=True)),
                ('date', models.DateField(null=True)),
                ('cik', models.IntegerField()),
                ('form', models.CharField(blank=True, max_length=10)),
                ('quarter', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
